packages:
  - "packages/ts-lazy-property"
  - "packages/ts-lazy-property/tests/fixture-suite"
  - "packages/ts-mixin-class"
  - "packages/ts-mixin-class/tests/declaration-fixture-suite"
  - "packages/ts-mixin-class/tests/fixture-suite"
allowBuilds:

overrides:
  "ts-patch>typescript": "6.0.3"

catalog:
  "@bryntum/siesta": "6.0.0-beta-1"
  "@types/node": "25.6.0"
  "ts-patch": "4.0.1"
  "typescript": "6.0.3"
